### ISSUE TITLE
Not writing to the Output File

### ISSUE THREAD

**Issue by sanjaypicmonic** [EthanHicks1/PythonBatchGeocoder#1]
I did not create a output file. At the end of program, there is no output file. it is not being created.
Even if i created an output file and then running the program, its not writing anything.

**Comment by EthanHicks1** [comment]
I just downloaded it today and ran it on my computer and it worked fine on the input.csv file provided in the repo. It created output files for me. Are you still having issues @sanjaypicmonic .

**Comment by elnils** [comment]
Unfortunately I face the same issue @EthanHicks1

**Comment by elnils** [comment]
Hey @EthanHicks1, i forked the files and tried again and still face the same issue. Do you have an idea what could be the issue? I do not get any error message and the code runs smoothly.

**Comment by EthanHicks1** [comment]
@elnils I will redownload the project and try to look at it this evening. I haven't messed with this project in over a year so hopefully, I can find the issue.

**Comment by EthanHicks1** [comment]
@elnils Ok, I updated the program to use **Python 3.8** ... I also added an output folder where it will place the files. I also added a **requirements.txt** which will make it easier to install the packages. Please note it will only write files when it finishes reading the file or however often you have it set to write backup files.

**Comment by elnils** [comment]
many thanks @EthanHicks1! it works smoothly now. I guess it was an issue with the file path in windows..

**Comment by EthanHicks1** [comment]
Yeah probably. Glad it now works.
